services:
  api:
    build: .
    container_name: embpredict
    image: embpredict-gpu
    restart: unless-stopped
    volumes:
      - ./:/app
    environment:
      PYTHONUNBUFFERED: '1'
      DEV_MODE: 'true'
      LOG_LEVEL: 'INFO'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '4g'

    ports:
      - 80:8808
    command: uvicorn --host 0.0.0.0 --port 8808 src.emb_predict.api:app
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    external: false
